# -*- coding: utf-8 -*-
"""Attendance_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1selX5X9iqlrTavIL5d9WEoKS9y0b9Qzt
"""

def calculate_attendance(total_classes, attended_classes):
    return (attended_classes / total_classes) * 100


def check_eligibility(attendance):
    if attendance >= 75:
        return "Allowed for exam"
    else:
        return "Not allowed for exam"


def main():
    student_name = input("Enter student name: ")
    student_course = input("Enter student course: ")

    try:
        total_classes = int(input("Enter total classes held: "))
        attended_classes = int(input("Enter classes attended: "))

        if total_classes <= 0:
            print("Error: Total classes must be greater than 0.")
            return

        if attended_classes < 0 or attended_classes > total_classes:
            print("Error: Invalid number of attended classes.")
            return

        attendance = calculate_attendance(total_classes, attended_classes)

        print("\nStudent Name:", student_name)
        print("Course:", student_course)
        print("Attendance Percentage:", round(attendance, 2), "%")
        print(check_eligibility(attendance))

    except ValueError:
        print("Error: Please enter whole numbers only.")

    except ZeroDivisionError:
        print("Error: Total classes cannot be zero.")


main()
