# -*- coding: utf-8 -*-
"""Attendance_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1selX5X9iqlrTavIL5d9WEoKS9y0b9Qzt
"""

def calculate_attendance(total_classes, classes_attended):
    return (classes_attended / total_classes) * 100


def check_eligibility(attendance):
    if attendance >= 75:
        return "Allowed for exam"
    else:
        return "Not allowed for exam"


def main():
    student_name = input("Enter student name: ")
    total_classes = int(input("Enter total classes held: "))
    classes_attended = int(input("Enter classes attended: "))

    attendance = calculate_attendance(total_classes, classes_attended)
    result = check_eligibility(attendance)

    print("\nStudent Name:", student_name)
    print("Attendance Percentage:", round(attendance, 2), "%")
    print(result)


main()